Support reading from stdin for longer input data.
antnks/wcf-deserializer pull request #7
Opened 2019-07-22 17:43 UTC by JarLob

Resolves #3

2019-07-22 18:17 UTC, antnks commented on src/NBFS/NBFS.cs
> -using System.Collections.Generic;
👍

2019-07-22 18:19 UTC, antnks approved these changes
Not good enough

2019-07-22 18:25 UTC, antnks commented
Smoke test failed:
```
$ dotnet run
Usage: NBFS [encode|decode] Base64Data

NOTE: All output, including exceptions, will be returned as a Base64 string.

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NBFSNetConsole.Main(String[] argv) in /home/dotnet/git/wcf-deserializer/src/NBFS/NBFS.cs:line 45
```

2019-07-22 18:26 UTC, antnks requested changes
$ dotnet run
Usage: NBFS [encode|decode] Base64Data

NOTE: All output, including exceptions, will be returned as a Base64 string.

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NBFSNetConsole.Main(String[] argv) in /home/dotnet/git/wcf-deserializer/src/NBFS/NBFS.cs:line 45

2019-07-23 06:23 UTC, JarLob commented
Main workflow was passing 😋 

> Smoke test failed:

2019-07-23 07:19 UTC, antnks approved these changes

2019-07-23 07:20 UTC, merged